name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: boshek/metrics@master
        with:
          token: ${{ secrets.NEW_METRICS_TOKEN }}
          
          user: boshek
          plugin_activity: yes
          plugin_languages: yes
          plugin_topics: yes

